trigger: none

stages:
- stage: BuildModelTraining
  jobs:
  - job: BuildModelTraining

    pool:
      vmImage: ubuntu-latest

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
        architecture: 'x64'

    # - script: |
    #     pip install azureml-core
    #     pip install azureml-pipeline-core
    #     pip install azureml-pipeline-steps
    #     az login --service-principal -u -p $(SECRET) --tenant
    #     python aml/training/pipeline/main.py
    #   displayName: 'Model training'
    - task: AzureCLI@2
      displayName: 'Model training'
      inputs:
        azureSubscription: 'sp'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          pip install azureml-core
          pip install azureml-pipeline-core
          pip install azureml-pipeline-steps
          python aml/training/pipeline/main.py
        workingDirectory: '$(System.DefaultWorkingDirectory)'
- stage: ReleaseModelDeployment
  dependsOn: BuildModelTraining
  jobs:
  - job: ReleaseModelDeployment
    pool:
      vmImage: ubuntu-latest

    steps:
    # - script: |
    #     az login --service-principal -u -p $(SECRET) --tenant
    #     az extension add -n ml
    #     az account set -s ""
    #     az configure --defaults workspace= group=
    #     az ml online-endpoint update  -f aml/deployment/endpoint.yml
    #     az ml online-deployment update  -f aml/deployment/deployment-power.yml
    - task: AzureCLI@2
      displayName: 'Model deployment'
      inputs:
        azureSubscription: 'sp'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az extension add -n ml
          az account set -s ""
          az configure --defaults workspace= group=
          az ml online-endpoint update  -f aml/deployment/endpoint.yml
          az ml online-deployment update  -f aml/deployment/deployment-power.yml
        workingDirectory: '$(System.DefaultWorkingDirectory)'
