trigger: none

stages:
- stage: BuildModelTrainingEnv
  jobs:
  - job: BuildModelTrainingEnvJob

    pool:
      vmImage: ubuntu-latest

    steps:
    - script: |
        docker build -f aml/training/env/Dockerfile -t huduaamlacr.azurecr.io/repo/train-env:v1 .
        az login --service-principal -u  -p $(SECRET) --tenant 
        az acr login -n huduaamlacr
        docker push huduaamlacr.azurecr.io/repo/train-env:v1
      displayName: 'Model training Env Build and Push'
